# Generated by Django 4.2.30 on 2026-08-14 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_scrutiny', 'Under Scrutiny'), ('forwarded_to_consultant', 'Forwarded to Consultant'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_scrutiny', 'Under Scrutiny'), ('forwarded_to_consultant', 'Forwarded to Consultant'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('note', models.TextField(blank=True, help_text='Optional note explaining the transition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='patents.patentapplication')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
