# Generated by Django 4.2.30 on 2026-09-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowevent',
            index=models.Index(fields=['application', '-created_at'], name='workflow_app_created_idx'),
        ),
    ]
