# Generated by Django 4.2.30 on 2026-08-13 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='public_documents/')),
                ('category', models.CharField(choices=[('policy', 'SJEC Patent Policy'), ('form', 'Patent Application Form'), ('nda', 'Non-Disclosure Agreement (NDA)'), ('guidelines', 'Patent Guidelines'), ('process_flow', 'Patent Process Flow'), ('fee_structure', 'Patent Fee Structure'), ('faq', 'FAQ')], max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('supporting_documents', 'Supporting Documents'), ('patent_form', 'Patent Form'), ('nda', 'Non-Disclosure Agreement (NDA)')], max_length=30)),
                ('file', models.FileField(upload_to='patent_documents/%Y/%m/')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patents.patentapplication')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
