# Generated by Django 4.2.30 on 2026-09-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='remark',
            index=models.Index(fields=['application', 'created_at'], name='remark_app_created_idx'),
        ),
        migrations.AddIndex(
            model_name='remark',
            index=models.Index(fields=['application', 'visible_to_applicant', 'created_at'], name='remark_app_vis_created_idx'),
        ),
    ]
